/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlPanelComponent: typeof import('./src/components/graph/network/ControlPanelComponent.vue')['default']
    GraphCardComponent: typeof import('./src/components/graph/network/GraphCardComponent.vue')['default']
    GraphConstructorComponent: typeof import('./src/components/graph/network/GraphConstructorComponent.vue')['default']
    GraphLibraryComponent: typeof import('./src/components/graph/GraphLibraryComponent.vue')['default']
    GraphNetworkComponent: typeof import('./src/components/graph/network/GraphNetworkComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModuleList: typeof import('./src/components/module/ModuleList.vue')['default']
    NamedGraphListComponent: typeof import('./src/components/graph/NamedGraphListComponent.vue')['default']
    NodeLabel: typeof import('./src/components/graph/network/template/NodeLabel.vue')['default']
    ProfileComponent: typeof import('./src/components/profile/ProfileComponent.vue')['default']
    ProfileDialogComponent: typeof import('./src/components/profile/ProfileDialogComponent.vue')['default']
    ProfileFilterComponent: typeof import('./src/components/profile/list/ProfileFilterComponent.vue')['default']
    ProfileInfoComponent: typeof import('./src/components/profile/ProfileInfoComponent.vue')['default']
    ProfilesComponent: typeof import('./src/components/profile/list/ProfilesComponent.vue')['default']
    ProfilesList: typeof import('./src/components/profile/ProfilesList.vue')['default']
    ProfileSolutionsComponent: typeof import('./src/components/profile/ProfileSolutionsComponent.vue')['default']
    ProfilesTableComponent: typeof import('./src/components/profile/list/ProfilesTableComponent.vue')['default']
    ProfileTaskComponent: typeof import('./src/components/profile/ProfileTaskComponent.vue')['default']
    PulginList: typeof import('./src/components/module/PulginList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInComponent: typeof import('./src/components/auth/SignInComponent.vue')['default']
    SignUpComponent: typeof import('./src/components/auth/SignUpComponent.vue')['default']
    TaskConstructor: typeof import('./src/components/task/constructor/TaskConstructor.vue')['default']
    TaskList: typeof import('./src/components/task/TaskList.vue')['default']
  }
}
