/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModuleList: typeof import('./src/components/module/ModuleList.vue')['default']
    ProfileComponent: typeof import('./src/components/profile/ProfileComponent.vue')['default']
    ProfileFilterComponent: typeof import('./src/components/profile/ProfileFilterComponent.vue')['default']
    ProfilesList: typeof import('./src/components/profile/ProfilesList.vue')['default']
    PulginList: typeof import('./src/components/module/PulginList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInComponent: typeof import('./src/components/auth/SignInComponent.vue')['default']
    SignUpComponent: typeof import('./src/components/auth/SignUpComponent.vue')['default']
    TaskConstructor: typeof import('./src/components/task/constructor/TaskConstructor.vue')['default']
    TaskList: typeof import('./src/components/task/TaskList.vue')['default']
  }
}
