/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ControlPanelComponent: typeof import('./src/components/graph/network/ControlPanelComponent.vue')['default']
    ExamComponent: typeof import('./src/components/exam/ExamComponent.vue')['default']
    GraphCardComponent: typeof import('./src/components/graph/network/GraphCardComponent.vue')['default']
    GraphConstructorComponent: typeof import('./src/components/graph/network/GraphConstructorComponent.vue')['default']
    GraphInputComponent: typeof import('./src/components/graph/GraphInputComponent.vue')['default']
    GraphLibraryComponent: typeof import('./src/components/graph/GraphLibraryComponent.vue')['default']
    GraphSolutionCardComponent: typeof import('./src/components/solution/GraphSolutionCardComponent.vue')['default']
    GraphTableComponent: typeof import('./src/components/graph/GraphTableComponent.vue')['default']
    GraphTaskConstructorComponent: typeof import('./src/components/task/constructor/graph/GraphTaskConstructorComponent.vue')['default']
    ImplementationTaskConstructor: typeof import('./src/components/task/constructor/implementation/ImplementationTaskConstructor.vue')['default']
    MaterialsCard: typeof import('./src/components/materials/MaterialsCard.vue')['default']
    PluginComponent: typeof import('./src/components/plugins/PluginComponent.vue')['default']
    PluginFilterComponent: typeof import('./src/components/plugins/PluginFilterComponent.vue')['default']
    PluginInputComponent: typeof import('./src/components/plugins/PluginInputComponent.vue')['default']
    PluginTableComponent: typeof import('./src/components/plugins/PluginTableComponent.vue')['default']
    ProfileComponent: typeof import('./src/components/profile/ProfileComponent.vue')['default']
    ProfileDialogComponent: typeof import('./src/components/profile/ProfileDialogComponent.vue')['default']
    ProfileFilterComponent: typeof import('./src/components/profile/list/ProfileFilterComponent.vue')['default']
    ProfileInfoComponent: typeof import('./src/components/profile/ProfileInfoComponent.vue')['default']
    ProfilesComponent: typeof import('./src/components/profile/list/ProfilesComponent.vue')['default']
    ProfileSolutionsComponent: typeof import('./src/components/profile/ProfileSolutionsComponent.vue')['default']
    ProfilesTableComponent: typeof import('./src/components/profile/list/ProfilesTableComponent.vue')['default']
    ProfileTaskComponent: typeof import('./src/components/profile/ProfileTaskComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInComponent: typeof import('./src/components/auth/SignInComponent.vue')['default']
    SignUpComponent: typeof import('./src/components/auth/SignUpComponent.vue')['default']
    SolutionGraphComponent: typeof import('./src/components/solution/SolutionGraphComponent.vue')['default']
    TaskConditionComponent: typeof import('./src/components/task/constructor/graph/TaskConditionComponent.vue')['default']
    TaskConditionListComponent: typeof import('./src/components/task/constructor/graph/TaskConditionListComponent.vue')['default']
    TaskConstructorComponent: typeof import('./src/components/task/constructor/TaskConstructorComponent.vue')['default']
    TaskGraphComponent: typeof import('./src/components/task/TaskGraphComponent.vue')['default']
    TaskGraphLibraryComponent: typeof import('./src/components/task/constructor/graph/TaskGraphLibraryComponent.vue')['default']
    TaskGraphPluginTableComponent: typeof import('./src/components/task/constructor/graph/TaskGraphPluginTableComponent.vue')['default']
    TaskImplementationComponent: typeof import('./src/components/task/TaskImplementationComponent.vue')['default']
    TaskImplementationPluginTableComponent: typeof import('./src/components/task/constructor/implementation/TaskImplementationPluginTableComponent.vue')['default']
    TaskTableComponent: typeof import('./src/components/task/TaskTableComponent.vue')['default']
  }
}
